sudo: required
services:
  - docker

before_install: 
  - docker build -t marianoucha/curso -f ./client/Dockerfile.dev ./client

script:
  - docker run marianoucha/curso npm test -- --coverage

after_success:
  - docker build -t marianoucha/multi-client ./client
  - docker build -t marianoucha/multi-nginx ./nginx
  - docker build -t marianoucha/multi-server ./server
  - docker build -t marianoucha/multi-worker ./worker
  # Log into Docker Hub
  - echo "$DOCKER_PASSWORD" | docker login -u "DOCKER_ID" --password-stdin
  # Take those images and push into Docker Hub
  - docker push marianoucha/multi-client
  - docker push marianoucha/multi-nginx
  - docker push marianoucha/multi-server
  - docker push marianoucha/multi-worker